edition = "2024"
max_width = 100
tab_spaces = 4
match_block_trailing_comma = false
use_field_init_shorthand = true
use_small_heuristics = "Default"
use_try_shorthand = true
newline_style = "Auto"
reorder_imports = true
reorder_modules = true
merge_derives = true

